version: '3.8'
services:

  #
  # Deploy a standalone instance of the Curity Identity Server
  #
  curity-idsvr:
    hostname: identityserver-internal
    image: custom_idsvr:7.2.0
    ports:
      - 6749:6749
      - 8443:8443
    environment:
      PASSWORD: 'Password1'
      STAGE: "${STAGE}"
      LICENSE_KEY: "${LICENSE_KEY}"
      IDSVR_BASE_URL: "${IDSVR_BASE_URL}"
      WEB_BASE_URL: "${WEB_BASE_URL}"
      LOGGING_LEVEL: 'INFO'

  #
  # Deploy a utility API used to create a GitHub pull request when configuration changes in the Admin UI
  #
  git-integration-api:
    hostname: api-internal
    image: git-integration-api:1.0.0
    environment:
      STAGE: "${STAGE}"
